### PR TITLE
Handle iTunes activity metadata in git #58

### PR DESCRIPTION
**Pull request by kelson42**

### CODE REVIEW

**Comment by kelson42** [comment]
@julianharty May you please fix the english?

**Comment by automactic** [comment]
@kelson42, @julianharty, would you mind to put the change log in `ProjectRoot/AppStore/WhatsNew`?

**Comment by kelson42** [comment]
@automactic OK to me.

**Comment by julianharty** [comment]
@automactic sorry for the delayed response, I was on holiday with my wife
and away from my computer. I've created a new PR with some edits to the
description. Would you prefer the file to be renamed to WhatsNew? If so, I
can do so or you're welcome to.

**Comment by automactic** [comment]
Welcome back! How was your holiday? 
Yes, WhatsNew does sounds better. I will rename it in GH-61

**Comment by julianharty** [comment]
Holidays are always great. Perhaps github notifications aren't the best
place to write about the details though :) We can discuss when we chat if
you'd like to know more...

**Pull request merged**
